# PotPlayer-like defaults + quality
vo=gpu-next
hwdec=auto-safe
profile=high-quality
keep-open=yes
keep-open-pause=yes
keepaspect=yes
keepaspect-window=no
osd-duration=900
osd-font=Malgun Gothic
osd-font-size=20
osd-color=#F2F0EC
osd-border-color=#000000A0
osd-border-size=1
osd-playing-msg=
save-position-on-quit=yes
resume-playback=yes
watch-later-options=start
volume=70
volume-max=150
sub-auto=fuzzy
audio-file-auto=fuzzy
secondary-sub-ass-override=yes
screenshot-format=png
screenshot-directory=~~desktop/
screenshot-template=%F-%wH%wM%wS-%wT
hr-seek=default
osd-bar=no
osc=no
cursor-autohide=1200
title=${media-title} - mpv
af=scaletempo2
scale=ewa_lanczossharp
dscale=mitchell
deband=yes
